# Generated by Django 5.2.3 on 2026-07-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('video_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('input_video', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('output_video', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('model_name', models.CharField(default='YOLOv8s', max_length=64)),
                ('line_y_ratio', models.FloatField(default=0.55)),
                ('conf', models.FloatField(default=0.4)),
                ('downward', models.BooleanField(default=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('by_class', models.JSONField(blank=True, default=dict)),
                ('frames_processed', models.PositiveIntegerField(default=0)),
                ('fps_avg', models.FloatField(default=0)),
                ('duration_sec', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Сессия обработки',
                'verbose_name_plural': 'Сессии обработки',
                'ordering': ['-created_at'],
            },
        ),
    ]
