# Generated by Django 5.2.3 on 2026-07-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingsession',
            name='snapshots',
            field=models.JSONField(blank=True, default=list, verbose_name='Скриншоты'),
        ),
    ]
